# blendshape group
lf_eyebrowBshAll_grp = ['lf_eyebrowAllUp_bsh',
						'lf_eyebrowAllDn_bsh',
						'lf_eyebrowAllIn_bsh',
						'lf_eyebrowAllOut_bsh',
						'lf_eyebrowInnerUp_bsh',
						'lf_eyebrowInnerDn_bsh',
						'lf_eyebrowMidUp_bsh',
						'lf_eyebrowMidDn_bsh',
						'lf_eyebrowOuterUp_bsh',
						'lf_eyebrowOuterDn_bsh']

rt_eyebrowBshAll_grp = ['rt_eyebrowAllUp_bsh',
						'rt_eyebrowAllDn_bsh',
						'rt_eyebrowAllIn_bsh',
						'rt_eyebrowAllOut_bsh',
						'rt_eyebrowInnerUp_bsh',
						'rt_eyebrowInnerDn_bsh',
						'rt_eyebrowMidUp_bsh',
						'rt_eyebrowMidDn_bsh',
						'rt_eyebrowOuterUp_bsh',
						'rt_eyebrowOuterDn_bsh']

lf_lidBshAll_grp = 	[	'lf_upLidUp_bsh', 
						'lf_upLidDn_bsh', 
						'lf_loLidUp_bsh', 
						'lf_loLidDn_bsh', 
						'lf_upLidTWF_bsh', 
						'lf_upLidTWC_bsh', 
						'lf_loLidTWF_bsh', 
						'lf_loLidTWC_bsh']

rt_lidBshAll_grp = 	[	'rt_upLidUp_bsh', 
						'rt_upLidDn_bsh', 
						'rt_loLidUp_bsh', 
						'rt_loLidDn_bsh', 
						'rt_upLidTWF_bsh', 
						'rt_upLidTWC_bsh', 
						'rt_loLidTWF_bsh', 
						'rt_loLidTWC_bsh']

lf_inBtwBsh_grp = [		'lf_upLidDnInBtw25_bsh', 
						'lf_loLidUpInBtw25_bsh', 
						'lf_upLidDnInBtw_bsh', 
						'lf_loLidUpInBtw_bsh', 
						'lf_upLidDnInBtw75_bsh', 
						'lf_loLidUpInBtw75_bsh']

rt_inBtwBsh_grp = [		'rt_upLidDnInBtw25_bsh', 
						'rt_loLidUpInBtw25_bsh', 
						'rt_upLidDnInBtw_bsh', 
						'rt_loLidUpInBtw_bsh', 
						'rt_upLidDnInBtw75_bsh', 
						'rt_loLidUpInBtw75_bsh']

cntr_lipsBshAll_grp = [	'mouthUp_bsh', 
						'mouthDn_bsh', 
						'mouthTurnL_bsh', 
						'mouthTurnR_bsh', 
						'mouthTurnF_bsh', 
						'mouthTurnC_bsh', 
						'mouthClench_bsh', 
						'mouthPull_bsh', 
						'mouthSad_bsh', 
						'mouthHappy_bsh', 
						'upLipUp_bsh', 
						'upLipDn_bsh', 
						'loLipUp_bsh', 
						'loLipDn_bsh', 
						'upLipAllUp_bsh', 
						'upLipAllDn_bsh', 
						'loLipAllUp_bsh', 
						'loLipAllDn_bsh', 
						'upLipAllCurlIn_bsh', 
						'upLipAllCurlOut_bsh', 
						'loLipAllCurlIn_bsh', 
						'loLipAllCurlOut_bsh', 
						'mouthA_bsh', 
						'mouthE_bsh', 
						'mouthFV_bsh', 
						'mouthI_bsh', 
						'mouthL_bsh', 
						'mouthMBP_bsh', 
						'mouthO_bsh', 
						'mouthS_bsh', 
						'mouthTh_bsh', 
						'mouthUWQ_bsh']

lf_lipsBshAll_grp = [	'lf_upLipUp_bsh', 
						'lf_upLipDn_bsh', 
						'lf_loLipUp_bsh', 
						'lf_loLipDn_bsh', 
						'lf_cnrLipUp_bsh', 
						'lf_cnrLipDn_bsh', 
						'lf_cnrLipIn_bsh', 
						'lf_cnrLipOut_bsh', 
						'lf_upLipCurlIn_bsh', 
						'lf_upLipCurlOut_bsh', 
						'lf_loLipCurlIn_bsh', 
						'lf_loLipCurlOut_bsh', 
						'lf_cnrLipPartIn_bsh', 
						'lf_cnrLipPartOut_bsh', 
						'lf_cnrLipPuffIn_bsh', 
						'lf_cnrLipPuffOut_bsh', 
						'lf_cheekUpr_bsh', 
						'lf_cheekLwr_bsh', 
						'lf_noseUp_bsh', 
						'lf_noseDn_bsh']

rt_lipsBshAll_grp = [	'rt_upLipUp_bsh', 
						'rt_upLipDn_bsh', 
						'rt_loLipUp_bsh', 
						'rt_loLipDn_bsh', 
						'rt_cnrLipUp_bsh', 
						'rt_cnrLipDn_bsh', 
						'rt_cnrLipIn_bsh', 
						'rt_cnrLipOut_bsh', 
						'rt_upLipCurlIn_bsh', 
						'rt_upLipCurlOut_bsh', 
						'rt_loLipCurlIn_bsh', 
						'rt_loLipCurlOut_bsh', 
						'rt_cnrLipPartIn_bsh', 
						'rt_cnrLipPartOut_bsh', 
						'rt_cnrLipPuffIn_bsh', 
						'rt_cnrLipPuffOut_bsh', 
						'rt_cheekUpr_bsh', 
						'rt_cheekLwr_bsh', 
						'rt_noseUp_bsh', 
						'rt_noseDn_bsh']

facesBshAll_grp = [		'faceSquash_bsh', 
						'faceStretch_bsh', 
						'noseSquash_bsh', 
						'noseStretch_bsh']
